version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - '8000:8000'
    command: uvicorn backend.api.app:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000

  pinecone:
    image: pinecone/pinecone:latest
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}